export type PitcherTotalType = {
  bb: number;
  bf: number;
  er: number;
  era: string;
  gamenum: number;
  gyear: string;
  hit: number;
  hold: number;
  hp: number;
  hr: number;
  inn2: number;
  innDisplay: string;
  kk: number;
  l: number;
  r: number;
  sho: number;
  sv: number;
  teamCode: string;
  teamName: string;
  w: number;
  wCg: number;
  wra: string;
};

export type FilterPitTotalType = {
  gyear: string;
  teamName: string;
  era: string;
  gamenum: number;
  wCg: number;
  sho: number;
  w: number;
  l: number;
  sv: number;
  hold: number;
  wra: string;
  bf: number;
  innDisplay: string;
  hit: number;
  hr: number;
  bb: number;
  kk: number;
  er: number;
};
