export type PitcherType = {
  babip: string;
  bb: number;
  bf: number;
  bk: number;
  bs: number;
  er: number;
  era: string;
  err: number;
  fip: string;
  fo: number;
  gamenum: number;
  go: number;
  gyear: string;
  havg: string;
  hit: number;
  hold: number;
  hp: number;
  hr: number;
  ib: number;
  inn2: number;
  innDisplay: string;
  kbb: string;
  kk: number;
  l: number;
  oavg: string;
  pcode: string;
  playerName: string;
  qs: number;
  qsPlus: number;
  r: number;
  ravg: string;
  sf: number;
  sh: number;
  sho: number;
  start: number;
  sv: number;
  svo: number;
  tugucount: number;
  turfSave: number;
  w: number;
  wCg: number;
  war: string;
  whip: string;
  winShares: string;
  wl: string;
  wp: number;
  wra: string;
};

export type FilterPitcherType = {
  era: string;
  gamenum: number;
  wCg: number;
  sho: number;
  w: number;
  l: number;
  sv: number;
  hold: number;
  wra: string;
  bf: number;
  tugucount: number;
  innDisplay: string;
  hit: number;
  hr: number;
};

export type FilterPitcherType2 = {
  sf: number;
  sh: number;
  bb: number;
  ib: number;
  hp: number;
  kk: number;
  wp: number;
  bk: number;
  r: number;
  er: number;
  bs: number;
  whip: string;
  oavg: string;
  qs: number;
  kbb: string;
};
