export type HitterType = {
  ab: number;
  babip: string;
  bb: number;
  bbkk: string;
  bra: string;
  cs: number;
  finalHit: number;
  gamenum: number;
  gd: number;
  gyear: string;
  h2: number;
  h3: number;
  hit: number;
  hp: number;
  hr: number;
  hra: string;
  ib: number;
  kk: number;
  ops: string;
  opsPlus: string;
  pa: number;
  pcode: string;
  rbi: number;
  run: number;
  sb: number;
  sbTryCn: number;
  sba: string;
  sf: number;
  sh: number;
  slg: string;
  spHra: string;
  war: string;
  winShares: string;
  woba: string;
  wrHit: string;
  wraa: string;
  xbhrun: string;
};

export type FilterHitterType = {
  hra: string;
  gamenum: number;
  pa: number;
  ab: number;
  run: number;
  hit: number;
  h2: number;
  h3: number;
  hr: number;
  rbi: number;
  sb: number;
  cs: number;
  sh: number;
  sf: number;
};

export type FilterHitterType2 = {
  bb: number;
  ib: number;
  hp: number;
  kk: number;
  gd: number;
  slg: string;
  bra: string;
  cs: number;
  sba: string;
  bbkk: string;
  xbhrun: string;
  ops: string;
  spHra: string;
};
