export type TTemaRank = {
  rank: number;
  teamName: string;
  game: number;
  win: number;
  lose: number;
  drawn: number;
  wra: string;
  ab: number;
  continue1: string;
  bra: string;
  lra: string;
  hra: string;
  er: number;
  run: number;
  r: number;
  hr: number;
};
export type TPicheringRank = {
  teamName: string;
  sh: number;
  sf: number;
  bb: number;
  ib: number;
  bbhp: number;
  kk: number;
  wp: number;
  sho: number;
  r: number;
  er: number;
  bs: number;
  whip: string;
  oavg: string;
  qs: number;
};
export type TBattingRank = {
  teamName: string;
  hit: number;
  h2: number;
  h3: number;
  hr: number;
  rbi: number;
  sb: number;
  bb: number;
  ib: number;
  hp: number;
  kk: number;
  gd: number;
  slg: string;
  bra: string;
  err: number;
  ops: string;
  hra: string;
};
export type TTeamVS = {
  drawn: number;
  lose: number;
  teamCode: string;
  teamName: string;
  vsTeamCode: string;
  win: number;
};
